QT.Prison.VERSION = 1.2.0
QT.Prison.MAJOR_VERSION = 1
QT.Prison.MINOR_VERSION = 2
QT.Prison.PATCH_VERSION = 0
QT.Prison.name = KF5Prison
QT.Prison.defines = 
QT.Prison.includes = /usr/include/KF5/PRISON
QT.Prison.private_includes =
QT.Prison.libs = /usr/lib
QT.Prison.depends = Qt5::Gui
