
#ifndef PRISON_VERSION_H
#define PRISON_VERSION_H

#define PRISON_VERSION_STRING "1.2.0"
#define PRISON_VERSION_MAJOR 1
#define PRISON_VERSION_MINOR 2
#define PRISON_VERSION_PATCH 0
#define PRISON_VERSION ((1<<16)|(2<<8)|(0))

#endif
